namespace: 
image:
  repository: 927974570874.dkr.ecr.eu-west-1.amazonaws.com/smdc/notification-streamer
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: aws-cred

tnsAdmin:
  enabled: true
  secretName: tns-config
  mountPath: /secret

globalEnv:
  enabled: true
  name: global-env

liveness:
  failureThreshold: 15
  initialDelaySeconds: 1800
  periodSeconds: 1800
  timeoutSeconds: 10

resources:
  limits:
    cpu: "100m"
    memory: "2Gi"
  requests:
    cpu: "50m"
    memory: "64Mi"

 
