namespace: 

image:
  repository: 927974570874.dkr.ecr.eu-west-1.amazonaws.com/smdc/nmswebs
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: aws-cred
  
app:
   name: nmswebs

db:
  NMS_DB_NAME: NMS5UX
  ORACLE_HOST: database
  ORACLE_PORT: "1521"
  TNS_ADMIN: /usr/share/instantclient/tns
  EMS6D: ems6d

tnsAdmin:
  enabled: true
  secretName: tns-config
  mountPath: /secret
  
kafka:
  kafka_broker: kafka
  kafka_port: "9092"
  
pvc:
  storageClassName: gp3-csi
  accessModes:
    - ReadWriteOnce
  size: "1Gi"
  
service:
   name: nmswebs
   type: ClusterIP
   port: 8081
   protocol: tcp

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false

resources:
  limits:
    cpu: "500m"
    memory: "1Gi" 
  requests:
    cpu: "250m"
    memory: "256Mi"

