storageClassName: gp3-csi

kafka:
  image: bitnamilegacy/kafka:3.7.1-debian-12-r9
  pullSecrets:
    - name: aws-cred
  storageSize: 5Gi
  failureThreshold: 15
  initialDelaySeconds: 1800
  periodSeconds: 1800
  timeoutSeconds: 10

env:
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

topics:
  enabled: true
  configMapName: kafka-topics

