namespace: 
storageClassName: 
pullSecrets:
  - name: aws-cred

image:
  repository: 927974570874.dkr.ecr.eu-west-1.amazonaws.com/smdc/user-login-logout
  tag: latest
  pullPolicy: IfNotPresent
 
globalEnv:
  enabled: true
  name: global-env

tnsAdmin:
  enabled: true
  secretName: tns-config
  mountPath: /secret

usersloginlogout:
  failureThreshold: 15
  initialDelaySeconds: 1800
  periodSeconds: 1800
  timeoutSeconds: 10

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

