apiVersion: v1
kind: Service
metadata:
  name: trapd
  namespace: {{ .Values.namespace }}
  labels:
    app: trapd
spec:
  type: ClusterIP
  ports:
  - name: trapd
    port: {{ .Values.trapd.port }}
    targetPort: 1024
    protocol: "UDP"
  selector:
    app: trapd
