apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.kafka.image }}
        ports:
        - containerPort: {{ .Values.kafka.port }}
        env:
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:9093"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:{{ .Values.kafka.port }},CONTROLLER://:9093
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafka.port }}
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        livenessProbe:
            exec:
              command:
                - /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafka.port }} || exit 1
            failureThreshold: {{ .Values.kafka.failureThreshold }}
            initialDelaySeconds: {{ .Values.kafka.initialDelaySeconds }}
            periodSeconds: {{ .Values.kafka.periodSeconds }}
            timeoutSeconds: {{ .Values.kafka.timeoutSeconds }}
        resources:
          requests:
            cpu: {{ .Values.kafka.cpu }}
            memory: {{ .Values.kafka.memory }}
          limits:
            cpu: {{ .Values.kafka.cpu }}
            memory: {{ .Values.kafka.memory }}
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka
      imagePullSecrets:
        {{- range .Values.kafka.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data

