apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  minReplicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      #securityContext:
        #runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        #allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          volumeMounts:
            - name: webc-pvc
              mountPath: /usr/local/tomcat/logs
              
            - name: config-volume
              mountPath: /usr/local/tomcat/conf/nms5wiC.properties
              subPath: nms5wiC.properties

            - name: config-volume
              mountPath: /usr/local/tomcat/conf/nms5wiN.properties
              subPath: nms5wiN.properties

            - name: config-volume
              mountPath: /usr/local/tomcat/conf/nms5pwd.properties
              subPath: nms5pwd.properties
          env:
            # Example 1: Static environment variable from values.yaml
            - name: ASD_PORT
              value: {{ .Values.asd.asd_port | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      imagePullSecrets:
        {{- range .Values.app.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app.name }}-config
        - name: webc-pvc
          persistentVolumeClaim:
            claimName: webc-pvc
          
