apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  #minReplicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      #securityContext:
        #runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        #allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
      initContainers:
       - name: db-updater
         image: {{ .Values.db.DB_HELPER_IMAGE }}
         imagePullPolicy: Always
         #command: ["/usr/bin/bash", "-c", "/smdc/init-scripts/all_script.sh || true; sleep infinity"]
         env:
            # Example 1: Static environment variable from values.yaml
            - name: ORACLE_HOST
              value: {{ .Values.db.ORACLE_HOST | quote }}
            - name: ORACLE_PORT
              value: {{ .Values.db.ORACLE_PORT | quote }}
            - name: ORACLE_DATABASE
              value: {{ .Values.db.NMS_DB_NAME | quote }}
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS
         volumeMounts:
            - name: random-mac-secret
              mountPath: /opt/secret/RANDOM_MAC_KEY
              subPath: RANDOM_MAC_KEY
            - name: shared-mac
              mountPath: /shared
            
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          volumeMounts:
            - name: webc-pvc
              mountPath: /usr/local/tomcat/logs
              
            - name: config-volume
              mountPath: /usr/local/tomcat/conf/nms5wiC.properties
              subPath: nms5wiC.properties

            - name: config-volume
              mountPath: /usr/local/tomcat/conf/nms5wiN.properties
              subPath: nms5wiN.properties

            - name: config-volume
              mountPath: /usr/local/tomcat/conf/nms5pwd.properties
              subPath: nms5pwd.properties

            - name: shared-mac
              mountPath: /shared
          env:
            # Example 1: Static environment variable from values.yaml
            - name: ASD_PORT
              value: {{ .Values.asd.asd_port | quote }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

      imagePullSecrets:
        {{- range .Values.app.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app.name }}-config
        - name: webc-pvc
          persistentVolumeClaim:
            claimName: webc-pvc
        #- name: db-secret
         # secret:
          #  secretName: db-secret
        - name: random-mac-secret
          secret:
            secretName: random-mac-secret
        - name: mac-extracted
          emptyDir: {}
        - name: shared-mac
          persistentVolumeClaim:
            claimName: shared-mac-pvc
          







