apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
        
      initContainers:
       - name: extract-tns-auth
         image: 927974570874.dkr.ecr.eu-west-1.amazonaws.com/smdc/alpine:latest # alpine
         command: ["sh", "-c", "tar -xzf /tmp/tns.tgz -C /usr/share/instantclient"]
         volumeMounts:
            - name: tns-config-auth
              mountPath: /tmp
            - name: tns-extracted
              mountPath: /usr/share/instantclient/tns
              
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/application.properties
              subPath: application.properties
            - name: tns-extracted
              mountPath: /usr/share/instantclient/tns
            - name: shared-mac
              mountPath: /shared
              
      # âœ… environment variables
          env:
            - name: TNS_ADMIN
              value: "/usr/share/instantclient/tns"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: DB_USER
                  
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: DB_PASS
          resources:
            requests:
              cpu: {{ .Values.resource.requests.cpu }}
              memory: {{ .Values.resource.requests.memory }}
            limits:
              cpu: {{ .Values.resource.limits.cpu }}
              memory: {{ .Values.resource.limits.memory }}
       ###########
      imagePullSecrets:
        {{- range .Values.app.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app.name }}-config
        - name: tns-config-auth
          secret:
            secretName: tns-config-auth
        - name: tns-extracted
          emptyDir: {}
        - name: shared-mac
          persistentVolumeClaim:
            claimName: shared-mac-pvc
          
