storageClassName: gp3-csi

kafka:
  image: 927974570874.dkr.ecr.eu-west-1.amazonaws.com/smdc/kafka
  pullSecrets:
    - name: aws-cred
  storageSize: 5Gi
  failureThreshold: 15
  initialDelaySeconds: 1800
  periodSeconds: 1800
  timeoutSeconds: 10

env:
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

topics:
  enabled: true
  configMapName: kafka-topics

