apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}            # <- default; can be omitted
  selector:
    app: {{ .Values.app.name }}             # <- must match Pod labels in the Deployment
  ports:
    - name: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}             # <- Service port (what clients use)
      targetPort: {{ .Values.service.port }}       # <- containerPort in the Pod (can be number or name)
