apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmsmnd
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmsmnd
  template:
    metadata:
      labels:
        app: nmsmnd
    spec:
      imagePullSecrets:
        {{- range .Values.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      volumes:
        {{- if $.Values.tnsAdmin.enabled }}
        - name: tns-secret
          secret:
            secretName: {{ $.Values.tnsAdmin.secretName }}
        {{- end }}
      containers:
      - name: nmsmnd
        command: ["/bin/sh"]
        args: ["-c", "/app/start.sh /opt/nms5ux/bin/nmsMnd"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
            exec:
              command:
                - /app/healthcheck.sh
                - nmsMnd
{{- toYaml .Values.liveness | nindent 12 }}
        envFrom:
        {{- if $.Values.globalEnv.enabled }}
        - configMapRef:
            name: {{ default "global-env" $.Values.globalEnv.name }}
        {{- end }}
        env:
        - name: HOME
          value: /tmp
{{- toYaml .Values.environ | nindent 8 }}
        volumeMounts:
        {{- if $.Values.tnsAdmin.enabled }}
          - name: tns-secret
            mountPath:  {{ $.Values.tnsAdmin.mountPath }} 
            readOnly: true
        {{- end }}

        resources:
{{- toYaml .Values.resources | nindent 10 }}

